LOAD DATA INFILE 'course.csv'
INTO TABLE course
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n';

LOAD DATA INFILE 'instructor.csv'
INTO TABLE instructor
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n';

LOAD DATA INFILE 'section.csv'
INTO TABLE section
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n';

LOAD DATA INFILE 'prerequisite.csv'
INTO TABLE prerequisite
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n';

LOAD DATA INFILE 'rating.csv'
INTO TABLE rating
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n';
